# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2'

services:

  # PHP & apache container using offical Docker PHP iamge
  web:
    ports:
      # Expose Emoncms to the world on port 80
      - 8285:80
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms:latest) if not Buildcontainer see Dockerflile
    image: openenergymonitor/emoncms:latest
    build: .
    volumes:
      # mount docker volumes persistant inside docker container
      - emon-phpfina:/var/opt/emoncms/phpfina
      - emon-phptimeseries:/var/opt/emoncms/phptimeseries
    links:
      # Link to MYSQL DB (see below)
      - db
      - redis
    env_file:
      # Use default enviroment variables file for dev
      - 'default.docker-env'

  # MYSQL Database
  db:
    # Official MYSQL docker image
    # To do: make compatiable with 5.7
    image: mariadb:latest
    environment:
      - "MYSQL_HOST=localhost"
    volumes:
      - emon-db-data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file:
      - 'default.docker-env'

  redis:
    # Official redis image
    image: redis:5
    volumes:
      - emon-redis-data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file:
      - 'default.docker-env'

volumes:
  emon-phpfiwa:
    driver: local
  emon-phpfina:
    driver: local
  emon-phptimeseries:
    driver: local
  emon-db-data:
    driver: local
  emon-redis-data:
    driver: local
